//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smsServiceCSharp.wsSMS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSMS.SMSServiceSoap")]
    public interface SMSServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/envioMessagem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long envioMessagem(string email, string senha, string mensagem, string numeros, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/envioMessagem", ReplyAction="*")]
        System.Threading.Tasks.Task<long> envioMessagemAsync(string email, string senha, string mensagem, string numeros, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/envioTeste", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string envioTeste();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/envioTeste", ReplyAction="*")]
        System.Threading.Tasks.Task<string> envioTesteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificaCredito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string verificaCredito(string email, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificaCredito", ReplyAction="*")]
        System.Threading.Tasks.Task<string> verificaCreditoAsync(string email, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificaStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string verificaStatus(string email, string senha, long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificaStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> verificaStatusAsync(string email, string senha, long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChecarRecebidas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChecarRecebidas(string email, string senha, System.DateTime DataInicial, System.DateTime DataFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChecarRecebidas", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ChecarRecebidasAsync(string email, string senha, System.DateTime DataInicial, System.DateTime DataFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChecarRecebidasData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ChecarRecebidasData(string email, string senha, System.DateTime DataInicial, System.DateTime DataFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChecarRecebidasData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ChecarRecebidasDataAsync(string email, string senha, System.DateTime DataInicial, System.DateTime DataFinal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSServiceSoapChannel : smsServiceCSharp.wsSMS.SMSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServiceSoapClient : System.ServiceModel.ClientBase<smsServiceCSharp.wsSMS.SMSServiceSoap>, smsServiceCSharp.wsSMS.SMSServiceSoap {
        
        public SMSServiceSoapClient() {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long envioMessagem(string email, string senha, string mensagem, string numeros, string id) {
            return base.Channel.envioMessagem(email, senha, mensagem, numeros, id);
        }
        
        public System.Threading.Tasks.Task<long> envioMessagemAsync(string email, string senha, string mensagem, string numeros, string id) {
            return base.Channel.envioMessagemAsync(email, senha, mensagem, numeros, id);
        }
        
        public string envioTeste() {
            return base.Channel.envioTeste();
        }
        
        public System.Threading.Tasks.Task<string> envioTesteAsync() {
            return base.Channel.envioTesteAsync();
        }
        
        public string verificaCredito(string email, string senha) {
            return base.Channel.verificaCredito(email, senha);
        }
        
        public System.Threading.Tasks.Task<string> verificaCreditoAsync(string email, string senha) {
            return base.Channel.verificaCreditoAsync(email, senha);
        }
        
        public string verificaStatus(string email, string senha, long id) {
            return base.Channel.verificaStatus(email, senha, id);
        }
        
        public System.Threading.Tasks.Task<string> verificaStatusAsync(string email, string senha, long id) {
            return base.Channel.verificaStatusAsync(email, senha, id);
        }
        
        public string ChecarRecebidas(string email, string senha, System.DateTime DataInicial, System.DateTime DataFinal) {
            return base.Channel.ChecarRecebidas(email, senha, DataInicial, DataFinal);
        }
        
        public System.Threading.Tasks.Task<string> ChecarRecebidasAsync(string email, string senha, System.DateTime DataInicial, System.DateTime DataFinal) {
            return base.Channel.ChecarRecebidasAsync(email, senha, DataInicial, DataFinal);
        }
        
        public System.Data.DataTable ChecarRecebidasData(string email, string senha, System.DateTime DataInicial, System.DateTime DataFinal) {
            return base.Channel.ChecarRecebidasData(email, senha, DataInicial, DataFinal);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ChecarRecebidasDataAsync(string email, string senha, System.DateTime DataInicial, System.DateTime DataFinal) {
            return base.Channel.ChecarRecebidasDataAsync(email, senha, DataInicial, DataFinal);
        }
    }
}
